openapi: 3.0.0
info:
  title: bluedart-clone
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: auth
  - name: users
  - name: shipments
  - name: statuses
  - name: payments
  - name: reports
paths:
  /auth/send-otp:
    post:
      tags:
        - auth
      summary: send otp for email verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: user11@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/verify-otp:
    post:
      tags:
        - auth
      summary: verify otp for email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: user11@gmail.com
                otp: '340569'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: user 11
                email: user11@gmail.com
                phone_number: '9873543234'
                password: '123456'
                roleName: Delivery Agent
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: adityasinghrajawat393@gmail.com
                password: '654321'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/logout:
    delete:
      tags:
        - auth
      summary: logout
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjEyODY0NiwiZXhwIjoxNzMyMTMyMjQ2fQ.Ho4OWc1EZTRiZxTuwhtaLwG69Rs7YjkbPDJswiXCXTc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - users
      summary: get all users (ADMIN)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTM5NTA3OSwiZXhwIjoxNzMxMzk4Njc5fQ.EwKnKl-c8V5MVXXhrwe-EJ1MU25WlCyG55Ql1J_Lvcc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - users
      summary: create user (ADMIN)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: user3
                email: user3@gmail.com
                phone_number: '8765434563'
                password: '123456'
                roles:
                  - Customer
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTU2MjQ2NSwiZXhwIjoxNzMxNTY2MDY1fQ.zHVXfj62RnbweSJ08OuKYd_Unz9xRQ2KW-1pJTxLAI8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - users
      summary: get user by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTM4MDU1MywiZXhwIjoxNzMxMzg0MTUzfQ.XK_3rZtzjnSHU2pOJ9dQatvFdNkQ_17gTU125P4POOk
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 7d17a949-d1bd-46ab-a826-9b5cba7d34c9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - users
      summary: update user by id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: user 11
                email: user11@gmail.com
                phone_number: '9873543234'
                password: '123456'
                roleName: Delivery Agent
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE2NjE1NCwiZXhwIjoxNzMyMTY5NzU0fQ.mdfr5nkgv28gb6sHHX4ryg1aWHA0RGbkRrLctpAFdEM
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: a2a84898-0f2e-4d94-8aae-134acad25e86
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - users
      summary: delete user by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTM5MzEzMSwiZXhwIjoxNzMxMzk2NzMxfQ.8DzPvgcLxtGxaOujYne9b8qSSuBrK7RtdcxxomrHH1g
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 93180d66-7648-47a6-b5fe-3d85f213941b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}/payments:
    get:
      tags:
        - users
      summary: getl user payments
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjEzMTM1MSwiZXhwIjoxNzMyMTM0OTUxfQ.EShleHqXxwo3sg771sBKWyWxJhzapsq7PrbseDsPjn0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 7d17a949-d1bd-46ab-a826-9b5cba7d34c9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/upload-document:
    post:
      tags:
        - users
      summary: upload document
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                document:
                  type: string
                  format: binary
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjEzMTM1MSwiZXhwIjoxNzMyMTM0OTUxfQ.EShleHqXxwo3sg771sBKWyWxJhzapsq7PrbseDsPjn0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}/verify-document:
    patch:
      tags:
        - users
      summary: verify document
      requestBody:
        content: {}
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/me:
    get:
      tags:
        - users
      summary: get current user
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE5MTYwMywiZXhwIjoxNzMyMTk1MjAzfQ.VcvDHN_IBm6ZK5z5ncgC4l52Slban0wuQWz_x7In84I
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments:
    post:
      tags:
        - shipments
      summary: create shipment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                pickup_address: 123 MG Road, Bengaluru, Karnataka, 560001
                delivery_address: 456 Park Street, Mumbai, Maharashtra, 400001
                weight: 5
                dimensions:
                  length: 4
                  width: 2.5
                  height: 2
                is_fragile: true
                delivery_option: Express
                preferred_delivery_date: '2024-12-10'
                preferred_delivery_time: '16:00:00'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTQ3NDAwMSwiZXhwIjoxNzMxNDc3NjAxfQ.7qJUU98RkQ_znWNt_JAmx4v70MWJQ0i2xWxSKSVi2hw
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - shipments
      summary: get shipments
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTQ4MDM5MSwiZXhwIjoxNzMxNDgzOTkxfQ.lGbFaQ5C2g1lnEu43PkA2JIyvCWR-yphP43cLG-DDa4
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments/{id}:
    get:
      tags:
        - shipments
      summary: get shipment by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: ada02826-6fd3-4a69-b047-783fad0cd507
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - shipments
      summary: update shipments by id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                pickup_address: 123 MG Road, Bengaluru, Karnataka, 560001
                delivery_address: 456 Park Street, Mumbai, Maharashtra, 400001
                weight: 5
                dimensions:
                  length: 4
                  width: 2.5
                  height: 2
                is_fragile: false
                delivery_option: Express
                preferred_delivery_date: '2024-12-10'
                preferred_delivery_time: '16:00:00'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTQ5OTQyNSwiZXhwIjoxNzMxNTAzMDI1fQ.cvnMhdfq_VVY8qetN1iBNRWYM3vxug--Pe-4ixAwFK8
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 7b98248a-4b58-49d6-9c2b-e073d1128ade
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - shipments
      summary: delete shipment by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: a8748547-99af-4401-ae78-331cfe2260b9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments/{id}/status:
    patch:
      tags:
        - shipments
      summary: update shipment status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: Pending
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: ada02826-6fd3-4a69-b047-783fad0cd507
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments/{id}/assign-agent:
    patch:
      tags:
        - shipments
      summary: assign delivery agent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                delivery_agent_id: a2a84898-0f2e-4d94-8aae-134acad25e86
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: ada02826-6fd3-4a69-b047-783fad0cd507
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments/{id}/statuses:
    get:
      tags:
        - shipments
      summary: get shipment statuses
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 463e31b1-857e-4688-a5ef-8232a4323343
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shipments/{id}/reschedule:
    patch:
      tags:
        - shipments
      summary: reschedule delivery
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                preferred_delivery_date: '2024-12-15'
                preferred_delivery_time: '14:00:00'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 7737248c-52b5-45ec-9c9b-199464b51f40
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /statuses:
    post:
      tags:
        - statuses
      summary: create status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shipment_id: 463e31b1-857e-4688-a5ef-8232a4323343
                name: Delivered
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTYzODg1NCwiZXhwIjoxNzMxNjQyNDU0fQ.fu9NNXH7K5eET38bw8E7dUuDLN94hCg8KsRrzIP2uzQ
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /statuses/{id}:
    get:
      tags:
        - statuses
      summary: get status by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1NTQ5OSwiZXhwIjoxNzMyMTU5MDk5fQ.qt3xZchCX2jASybGfGkZu1M5DY0sZtVMiIZxaLTyaK0
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 2788ef36-9834-4171-b183-caf1af2840ab
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - statuses
      summary: delete status by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payments:
    post:
      tags:
        - payments
      summary: create payment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shipment_id: ada02826-6fd3-4a69-b047-783fad0cd507
                method: Online
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzMTgwZDY2LTc2NDgtNDdhNi1iNWZlLTNkODVmMjEzOTQxYiIsImlhdCI6MTczMjE2OTIyOSwiZXhwIjoxNzMyMTcyODI5fQ.tQieXBj1l9sYJcn3ffGt5yjKa_v-lJbaSZpXJoPjUTE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - payments
      summary: get payments
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTc0NDk2MiwiZXhwIjoxNzMxNzQ4NTYyfQ.axEXhdQ-5AV0XDynYLyryiJongIRQG2Njxh5b78oqLE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payments/{id}/status:
    patch:
      tags:
        - payments
      summary: update shipment status on COD
      requestBody:
        content: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzMTgwZDY2LTc2NDgtNDdhNi1iNWZlLTNkODVmMjEzOTQxYiIsImlhdCI6MTczMjE1OTEzNywiZXhwIjoxNzMyMTYyNzM3fQ.OBclDN2QxzXCvYPXFtt7FBfFbis7xReBy8KrsxBKqj8
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 2234367b-7790-4ddc-a4d5-766040deadeb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payments/{id}:
    get:
      tags:
        - payments
      summary: get payment by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE1OTkxMywiZXhwIjoxNzMyMTYzNTEzfQ.YS7q_SlZ0OPrzsQarVtkJRy827w9Mv3YrOiXQV85F_8
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 2234367b-7790-4ddc-a4d5-766040deadeb
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /reports/shipments:
    post:
      tags:
        - reports
      summary: generate shipment report
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                startDate: '2024-01-01'
                endDate: '2024-11-30'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMjE2NjE1NCwiZXhwIjoxNzMyMTY5NzU0fQ.mdfr5nkgv28gb6sHHX4ryg1aWHA0RGbkRrLctpAFdEM
        - name: startDate
          in: query
          schema:
            type: string
          example: '2024-01-01'
        - name: endDate
          in: query
          schema:
            type: string
          example: '2025-04-01'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /reports/customers:
    post:
      tags:
        - reports
      summary: generate customer report
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                startDate: '2023-01-01'
                endDate: '2024-12-31'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkMTdhOTQ5LWQxYmQtNDZhYi1hODI2LTliNWNiYTdkMzRjOSIsImlhdCI6MTczMTg1ODI5OSwiZXhwIjoxNzMxODYxODk5fQ._4qftoDlsY75khSSiWZilGh7wa2xkNbzlIGtk8_Q7hU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
